//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CovidAppV5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Case_Log
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Division_District { get; set; }
        public string OrgNumber { get; set; }
        public Nullable<System.DateTime> DateOfTest { get; set; }
        public Nullable<System.DateTime> DateOfExposure { get; set; }
        public string NumberOfExposed { get; set; }
        public string Notes { get; set; }
        public string PathToFile { get; set; }
    }
}
