//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CovidAppV5.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Covid19Entities : DbContext
    {
        public Covid19Entities()
            : base("name=Covid19Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Case_Log> Case_Log { get; set; }
        public virtual DbSet<Emergency_Leave> Emergency_Leave { get; set; }
        public virtual DbSet<Family_Leave> Family_Leave { get; set; }
    }
}
